"""Render attribution directly from successful collection records."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
models = json.loads((root / "collection/models.json").read_text())
lines = ["# Sources and attribution", "", "All outputs were generated locally on 2026-09-09 using public Hugging Face model snapshots. Links below pin the model revision rather than a mutable model name. Provider/tool for every execution: local Hugging Face Transformers on the contributor's workstation; the named model organizations did not host these requests.", "", "| System/model | Revision | License in model metadata | UTC collection start | New tokens | Stop |", "|---|---|---|---|---:|---|"]
for model in models:
    response = json.loads((root / f"collection/runs/{model['slug']}/response.json").read_text())
    license_name = "TII Falcon-LLM License 2.0" if model["slug"] == "falcon" else model["license"]
    lines.append(f"| [{model['model_id']}]({model['source']}) | `{model['revision']}` | {license_name} | {response['started_utc']} | {response['generated_tokens']} | {response['termination']} |")
lines.extend(["", "## Access, ancestry and licenses", "",
    "The publishers are XHToken (Spark), Qwen/Alibaba, Microsoft (Phi), Hugging Face (SmolLM), IBM (Granite), Technology Innovation Institute/Falcon-LLM Team, TinyLlama and H2O.ai (Danube). These are eight distinct named projects/checkpoints, not eight proven independent training lineages. TinyLlama's card states it adopts the Llama2 architecture/tokenizer; Danube3 adjusts the Llama2 architecture and uses the Mistral tokenizer. Shared architecture, synthetic training material and training-data overlap limit independence. No frontier-service names are used to label local outputs.", "",
    "License metadata and public model cards were inspected before use. Falcon is not Apache-2.0: its card links the [TII terms](https://falconllm.tii.ae/falcon-terms-and-conditions.html), including the applicable acceptable-use conditions. The Falcon-LLM Team's [release article](https://huggingface.co/blog/falcon3) is an additional attribution source. The intended use is lawful local architecture research. Model licensing is not a warranty that generated text is correct or unique. We redistribute generated proposals and small collection records, not model weights or the full downloaded model-card archive.", "",
    "## Runtime and evidence", "",
    "The responses record Python3.13.5, Windows, an NVIDIA GeForce RTX4070, CUDA12.8, torch2.8.0+cu128 and Transformers4.57.1, plus exact supporting package versions. Each response is the authoritative runtime record. Danube additionally required sentencepiece0.2.2 and protobuf7.36.1 before its successful invocation. The collector remains the same for all eight successful runs; its SHA-256 is recorded in every response. No model was re-run after producing a completed response.", "",
    "`request.json` stores the exact user message, rendered chat prompt, input IDs and generation settings. `response.json` stores generated token IDs, unedited decoded text, timestamps, stop condition and hashes. `model-files.json` records the actual weight/config/tokenizer/custom-code files used locally. File hashes can establish a match to these records but cannot independently attest execution or validate claims in generated text.", "",
    "## Edits and byte handling", "",
    "Raw decoded outputs were not rewritten, corrected, translated, continued or deduplicated. Special tokens remain in raw_outputs; readable.txt removes tokenizer special tokens only. The collector wrote text on Windows, which can serialize newlines as CRLF. Its output_sha256 is over the decoded UTF-8 string (LF), while request_sha256 and the packet manifest are over actual file bytes. verify_packet.py checks both deliberately. Packet .gitattributes prevents Git from silently normalizing preserved evidence. Line references in comparison.csv count text lines after universal-newline decoding.", "",
    "Analysis, comparison assessments, synthesis and scripts were prepared with Codex, separately from the eight recorded generations. No newly performed human review is claimed. The model assertions that components are implemented or benchmarks achieved have not been promoted to facts. Failed downloads/tokenizer setup and other incidents are disclosed in collection/incidents.md.", "",
    "## Repository and external references", "",
    "- [Original task and acceptance criteria](https://github.com/aLexzzz430/Cognitive-OS/issues/5).", "- [Inspected repository baseline](https://github.com/aLexzzz430/Cognitive-OS/tree/e20d2ff4d5c84d4c11c87218c4ae9a04ab0046ca).", "- Source paths supporting integration observations are linked in synthesis.md. Those observations are separate from model output.", "- No proprietary prompts, private API output, credentials, account screenshots or private customer data were used. Existing competing submissions were not used as sources for model outputs or the comparison.", ""])
(root / "sources.md").write_text("\n".join(lines), encoding="utf-8")
print("Wrote sources for", len(models), "successful model records")
